-- AlterTable
ALTER TABLE `user` ADD COLUMN `fatherName` VARCHAR(191) NULL,
    ADD COLUMN `firstName` VARCHAR(191) NULL,
    ADD COLUMN `lastName` VARCHAR(191) NULL,
    ADD COLUMN `name` VARCHAR(191) NULL;
